
CREATE TABLE Actor (
    Name VARCHAR(40),
    Movie VARCHAR(80),
    Year INT NOT NULL,
    Role VARCHAR(40)
);

LOAD DATA LOCAL INFILE "~/data/actors.csv" INTO TABLE Actor
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
