
CREATE TABLE Actor (
    Year INT NOT NULL,
    Name VARCHAR(40),
    Movie VARCHAR(80),
    Role VARCHAR(40),
) ENGINE = INNODB;

LOAD DATA LOCAL INFILE "~/data/actor1.del" INTO TABLE Actor
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';