-- load.sql
-- kaitlyn cason : 204411394
-- alexander waz : 504480512

LOAD DATA LOCAL INFILE "users.csv" INTO TABLE User
FIELDS TERMINATED BY '*' OPTIONALLY ENCLOSED BY '|';

LOAD DATA LOCAL INFILE "items.csv" INTO TABLE Item
FIELDS TERMINATED BY '*' OPTIONALLY ENCLOSED BY '|';

LOAD DATA LOCAL INFILE "bids.csv" INTO TABLE Bid
FIELDS TERMINATED BY '*' OPTIONALLY ENCLOSED BY '|';

LOAD DATA LOCAL INFILE "categories.csv" INTO TABLE Category
FIELDS TERMINATED BY '*' OPTIONALLY ENCLOSED BY '|';